# Generated by Django 2.2.4 on 2019-08-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('y_variable', models.TextField(blank=True, null=True)),
                ('variable', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(blank=True, null=True)),
                ('training_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='NOTSTARTED', max_length=50)),
                ('model_address', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpot_app.Dataset')),
            ],
        ),
    ]
